apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
spec:
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-external
subsets:
  - addresses:
      - ip: 192.168.4.185
    ports:
      - port: 8006
        protocol: TCP
