apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    server_url: https://headscale.{{ .Values.domain }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    derp:
      server:
        enabled: true
        region_id: 999
        region_code: "homelab"
        region_name: "Homelab"
        stun_listen_addr: 0.0.0.0:3478
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
    dns:
      magic_dns: true
      base_domain: tail.{{ .Values.domain }}
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8
    log:
      level: info
    oidc:
      only_start_if_oidc_is_available: true
      issuer: https://keycloak.{{ .Values.domain }}/realms/homelab
      client_id: headscale
      client_secret_path: /etc/headscale/oidc-secret
      scope:
        - openid
        - profile
        - email
      strip_email_domain: false
    policy:
      mode: file
      path: /etc/headscale/acl.yaml
  acl.yaml: |
    acls:
      - action: accept
        src:
          - "*"
        dst:
          - "*:*"
