apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-secret
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgC2y5cLmXLJowSWRDuACB9M9TYb3iE7MSsy4Ta0vsn+t1Yr2xxte6hGmoFp5OaaWKP/pgUDpFFff101+7I8Li/r44N2TuxMDSzImDfIwflw3QZpO6r1xq7LRPgb05c5Q51a0ayIPh/aAXZC4EqXFnKes7n0f0hhjugSTjdOAo1jA2sZ/pbQ9Q0GlwAYmuq3rhFAht/UWfXuNQA/+ZPSiytMfqe/RkygwMD41lnAOphQ4lof3MGJhv6Ou4O/kEF78aTvBl2YSyC9/DejMYf6OdDxPKauIIx0Lf5VVIq0gRqzWomqGCT3IYj0PjzxmbsG21R/pt3mArAyoasLnWHbiegh3HCc/78GtvATdHVlMFnascvPKoea9aGSk4mujDO5Wj/8/oIhcrgI0NYjX6YWOUS+ioqQHfxcX3tuXlaMS6KVV6XpEHUee3OHdWb/ypGx5sXOJDcqMyoBrFmG2Y4cgen7fZ53JwWMdo9gdCegVrHDSmXEZGadoergCtvxr3RcKlY3hqqvn09RMIbJpAIw1bPMaje06BWEaOlzpzTgAC6mpQZB3e+G7f0c49BzyIahk2gLg+BfHOs3Gq2Ox5qOu7voRN0VdoTVSltM3HtKlnQnHzpELKG0YJ9KZ3MpYWdikPWM9NEXHhYzv3UYAQtDxBb0C0Ev6PhgHCBUkdDUy+SzIX2oqqkkKEnR1uiIgAGevGQz+2oIUCfoDKrUT2zXJ1Ih4GXq7tF2fS2GI8PoMv33gQ==
  template:
    metadata:
      name: headscale-oidc-secret
      namespace: headscale
