apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-subnet-router-auth
  namespace: headscale
spec:
  encryptedData:
    authkey: AgDKqMzwhP/NmOyTHxc3Vj2BqjdtHNLI9WvrDuDHOohYojP5BWoyXICQeNXnRC+/nsWIVjinJrTUfl5GbbgiQjx9ibpiouiRlPh6BpxG1f8g/e74/prnuXt6dMG496nOz+qDyub1ynm4cAFzfOR2S9HZGh1DEytruuAmp+r0enaJD2GoeD7E8pPKDKsrT5OWmmXMgRSPmeb9l0pm+p9BEHyYWBAIe24Nsz+4pcCmG2PokrGIz85iRh+pJSN7VDxcLFksIQzfWgaqsRQIEoxkNYpyZamCNuBVE4owb1ZJSzdiY2fh7gwD2zIkO7lRUxYyzfML0lzJb4VGrP3iUH8+J/aTXUKBesSyBUtzlycE7iA2oG7ggIEPcJzKmffWBxqjDQ/12SMQA/TPQFew5IIPWW3b0bA9JILPiGj422DXRjQoImuX6A7yCkMUdpwjYTmyL+IDcCmJ2GwDjA5fHZjBV8J5xaeWSu8xiQ+uXOROSAMyr9VnIlqeqaQO3/Sk65IiCeHf/8FEF3MRChwKeFsZA90FHN2Qt7oSqHU20FK+w2ZolPj8fs7msy13+Uj8qiZi21hoAW5+lpc99J7Ib4d4+N/nR5jopo0nuP3yuEDzKtwRpUbSmAWGNw0BsJuVbiPCh7E89TUJu6cGAgeZJU5OtcZb34rB9+9jDg5A0x8C74K5NJ6ikRyeK7Iyl6LtdlSwYJUAjYTEsDLJvvOjB69nTSyYN/hhvGZoxpOYxNNxkxpsiQss7CWl1YeHvyp1Ib1187I=
  template:
    metadata:
      name: tailscale-subnet-router-auth
      namespace: headscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  labels:
    app.kubernetes.io/name: tailscale-subnet-router
    app.kubernetes.io/part-of: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale-subnet-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale-subnet-router
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-subnet-router-auth
                  key: authkey
            - name: TS_LOGIN_SERVER
              value: http://headscale.headscale.svc:8080
            - name: TS_ROUTES
              value: "192.168.4.0/24"
            - name: TS_USERSPACE
              value: "true"
            - name: TS_HOSTNAME
              value: "k8s-subnet-router"
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
          volumeMounts:
            - name: state
              mountPath: /var/lib/tailscale
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
      volumes:
        - name: state
          emptyDir: {}
