apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-subnet-router-auth
  namespace: headscale
spec:
  encryptedData:
    authkey: AgCF6iFi3BftLsqw/Ntw3dbxkPmZR1dKnvCcz9cfVueTEc/DgbPlZ5jWmtkg340RfOP9zjPGp8CYBMfP9r00AM2AhLPOEog4fvIMXTi2mdMIXOelO/Sdi9lDNCHnWI1t8SbwoPgEgGYXFny7tAnz4+8WTj8csWd1gO8MnxBLC7rnmbmzYpCovwa0iXKZXnLnaUP0X0t/udf30HHN/pt18wN/0cEbGaqzau/Z/QVbiI/dzTpz4xsXgYlF9KkbsVEjC3Hh1lASFrLfYl3Ss7FC8vqQ4Vuzh3KqaXg0G4C0ugYYWecenOqc1/sh8rqb7LcpLvSttt+Etk9d6f0sF5i7eW4AicLIAIE7Cbue5hfP8IxUy1VDeIj/tSB0qtj/bPWV+jWnxbPaPJLKZm258KKgH9H9IvHngdAEkbxVCopErflLdYLd5Hkfmf7vPUe5lL5F4IxMDe7Am1/Z4XhNJXUoR0Qj2V8OHmT3b6fOsk0gDJCL2sWspuCwqzaRjV+1GF8VELTHTaIivMem+L0K2LAHtH/XbnpyCQ+vA4BGJNkkSbGgMxW74G9cHcPDJ7Y6iGqn/+M+9L/e4hv/I3QMR98npEo+sXKXtagxS7OCW+4ogST6SI0ajV/+zBgAp6Ffs86Fl+zn29oj4UkJ/T+h8J9mxdBEqzXye1Nph7qPguWNZ74pP1QD9nW8LyhWRtZ4otUpywJhS6NkmcgvIAW8iv/EFq1H65qlnXeAJ3Sb1pNgS/lvCPOz/byHdJtNH4iS6/BvoEA=
  template:
    metadata:
      name: tailscale-subnet-router-auth
      namespace: headscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  labels:
    app.kubernetes.io/name: tailscale-subnet-router
    app.kubernetes.io/part-of: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale-subnet-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale-subnet-router
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-subnet-router-auth
                  key: authkey
            - name: TS_LOGIN_SERVER
              value: https://headscale.{{ .Values.domain }}
            - name: TS_ROUTES
              value: "192.168.4.0/24"
            - name: TS_USERSPACE
              value: "true"
            - name: TS_HOSTNAME
              value: "k8s-subnet-router"
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_KUBE_SECRET
              value: ""
          volumeMounts:
            - name: state
              mountPath: /var/lib/tailscale
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
      volumes:
        - name: state
          emptyDir: {}
