---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis
spec:
  encryptedData:
    redis-password: AgATTmUaAFHKTJHhFkTzekdIlNSucIYYkwb3hbdzgO3vJOXfUV7Y1XoezO2cflhi5GNIHPvrvZ9dtZS6iKJxd7ER10JXSUWoNze6FGHmQ1O7kUm28Y6x7tePLLPO5UWvAs/UGDW27EKLvIJ+kOWLz2RfkwPAlHY6NVJ60ed+73709AMXNHFP9JgBTEwyM7Ni+N+Jx/d/pglemGGXqfNoGRiDRET4Vb31tXRJ7qnF7gqNYcwVGnl7J2WcOtKWQtaIx1n7noizIazLpe6X9OsDy4CE7OItRSLYNKF6Iqwsnl8LGVOUDWPJY6rHc4XvEX4dsIFx+ND+bcxJyEFhrY8cyhqe4N3JMpHW0FeQvJaPXsmh8nm81O2aysxXtJ/q78vSBLDvs5+BeNGLwKzoRjD3e8Ua26lWmnxqy9hg2Xc8aVI4Up+O5z0sPu3HZIgE5YJY/mhlrHe2MwiyurQbSSGzie9G5ifP98mv4XIRxDxdfdLtb7ehtQtQ0QJ6CeArC/e/bNhFC/dg118v6svqknLFXIStCQOSHoV+EbOGoqGDWTA5w/B+b5simTkYqTAbLzoJRLvjLPyy9BGFALa27j0WbHLcRHQaNwiBXAbFdxJ4/OSN97JefI+aAbvWZdaWPIY+JbMA85awL0tylpM2PEL/FgWRE9/DUTKaOA5rj/MJQ2zI9LZWOgY31O2cm08MtcNj9cB5JXY5IQaasDuSCNJ1eVq59ySnik4Gtnh4SXTHLYraicvIvLWHMByN
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis
