---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBlLyAXhupj2zg2fxJ88EqBIkGmoXv30oFaLvDib1NynjiwMrrkuMtan9CnEl1SpQ+KJqa1Cp0ci5aQpDvPiI1Q2ZPl/oaPHnS3ikTKezXY3XNJVxdUaQTrtKqeINsmUqo3sYjuja6c7K+KH3g6fw77kwTTBgq058V+Zuq9LOcEFVCxX9/CUx+Hb/Uc7+nSoU7QfORcIriDYu8b+h8DdC39w/YTPEuzU/3cJNLmBDq0vpvxihW4G14vaa+dxxTZfbOlZM6P7MUIKSwPkyHiSdHM8/dCTHPV50C2X0A3oc+HwghJe42xomey7ynAu4BVmtpC2HOQah7MGdOB8QMHiJjrWgPE9nKA9WcYSbXTftvoehmatyMqzBPM4/ehH6aJwrBHkgUMhMYcu2TjhM1P7dLhAxSpbZ7ymbpQYlS1Oz0qdJWWv4Jjhz1m0aq8xS1Xd4JYjLFBatmVH7gRbFzAM3Kucl1Qp6SnLk76y+oh9hCkZTixQ+Sr+OU1ng+xurwqj5W2UkybPjpGeP64RC3+nEWhCu/FTB4ikbdVVfseGGeHmT3fh7ne+548tMD2z99dIHihoEr/V324kcZgbUFRf6dsmdXmkdHB+FPaZKD1JWxDUytUerYSmu5qJLxCyuByjNE0MX8PLp2mBB6SKnZvK/njKtFrM+L7QOYZFUNxV54X7Zi6jM88PU7VlDMt8DeEya0jxejnh/XRITKKLOzptV+oxET1Z7ZCF6K4XfJTPUsTQpYvVuGo96xb
    postgres-user: AgBjyyu+yZs6RRBw2+VRlbZGG2wV06eRJVvdotLL4n9jmm0Kin4/bJ9mEz9qvtL+40zpYUr7jkodhEQEiHuPRaU2E1ZQOGdDi7O4beN+fekbNMPikFMoDV3rmFCHYUs1m7eFjNOFTzIyEUn9C2iH0ao0Mi25moZNUDz31z3VXa38W6czm/ZdH861hJFQHuXkDKLpQBR5lRnG2YcG/NwdpGMhSA368SGIHH90BNyVATGixA6xHtQ+1t0YUuPeWcSxpB5m3jJ3+R9Ls/OQEp+hiWPh0HCB4Qla4Jn5a2HIGRrtjLTxrm30UyLHFd3ndJi3K0QpO1HrOpHoRY+Vbl+mOHYB/A4s7VVscWi4tnSprX48FgvKtRZqiPaGEqRwSvUdpycT1Kt/AGn3e/OpAbE16gd0dGBciWt1Is95ki78hZCAEo+xzID79C4GH3/p7/fFcZt0QfKREhNhGjvxN+r1BaO8QEibUIbcvIaisdmkX0duQX2I7vleB93TWHpfyC1XXMNoL0uyZKyMzporwleqyryGA9r9SL2F/fjp2YahwkNH1AAEv6w1uLRjMHlP/GOOe7t4VQTx5HIBD5zy6Tot5K6k3/0/P/Z0yXKjRi7UA8oJVK62hLCeO/asMMP+TQK58cvDK44rk1fz2xtV8OrvL3t7oIuj32vgiHRKwy7RaXuOHHAG8M8O7fkmgBur/HAJxeQbUBPF0ngiHw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: postgres
