apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgBVtRhF9Rf9H3uH0t3fcB76lUeTym+lajCuF598sOHuU9x6qv8/iBZxtKSgQfpXwxw2gP2TimDgBoZ4UnxADJJIRlpranw5fq3pEYC4/w2/9I0CBvxYFJLrfcOdoxd7gLoWl4EOVYqZ425VYf5o9ykh5Zw1Ef+9dX+9mo0QVKr95xI+jtO2rNc8Z98cMEho5/eUukocfnnAWgcsj9dhXoKaq1fASehnIg5BBc/L8A0AVx59fZDZd20Qa8DUG8Mror1gF1L6X8JcFxdiyRCm79uVb2SJ3RceWkcAK5Ue4oNdwvc4F18dReMXySmtf8x4Qyou4fzB0qOfW8Tj+le/VQ21jVKZRmy+wLd68uzkJYv2uDPXVCnmx6xgSbw3SPwjG/NWs8qypQo/jSmBrivNaBB6wwuLy6yF24hf3C/ZRo5KB32qBfH7gJEAxGS54hwi6vRPdqI0gGvUEc6EijIZvCsZMoJrEREbCKovCsXaKAVL1e1jNS9WpxshTSZEtxh6u3CH9+ezAqIcPuCQG2uZmUc7gM3COOxYrtRtiXb0eRFiFP5/fWEP/YW4oRBwa8PHfMz1tA8JtxA1J0SqyyH5x/65s/S0f7lHSzokXix8O42yq2Jjivmaomb+6JubSkrlKP5GAyC8lUrPDCK8R5K0gw8Zl9yY62P00dCXAZRYrRm79uaYWbNPiBz5vmVCGRPHZLqyllHu/hNJtmgA/f64zF99TWvXGduVp2o=
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgDLo7SRQQCKDLGTMUFf2NrUwUdd6KgpQFVRfuH4XSyDot3sY2F00D7dJ8QwRNYNrByxfCGSdGk+w1xA+53vrfv88vSQ2Y47o73vwZ/uLlCpyiUKeahvsvKbGG1YKoBR6loRSFcOHBYz3f4CXCTT1dCi8hWSv2ujXjnzfaATzKNCD57ub+ycWAKSyLYzNgGJPXNp5Gmx9um6R+xAROM6HUT5BP+ouNjhO04aQGfNFvgYkbOpDbmV5INBEcbzTiXdonr9b4btv2OgDYFsKNHylZFc6Lff8kbJlXCDCxTTbvnKQSLdwUL6ZAYE1Sv2xxpFCLD4u+PZ/sh1IYky5/HXEUyKp2o9mwu7mxRyzM56lnpJsg2JH2SvILN9PaK81Iu9tTlsILJt/aXzcnsd2F89J9uLA1vIagOi5HgLFU8KZLcdZnyi27y9JGpLJKl3mYkO2nwQDX3v+Gcg0yh05q/IF9Tf8c4AxOgWsQ9WlYi9oylgNFTTjgjwIsFGLM1abCwmpt2y7cAp87/7LPNtkDdudfjWN7qhEbbiKK6QWwDGU9QVPZX4xlsaqFQEkCALHcn2Q8vqfrE2gDRUOI2j5a75xELum9oUrcCj9sR+GPb8j4MqyLzmm98DsMtPWTht+jXUlXhSh+isLq0fp4O5RPTVUt2LAiKOI62ApqBMZv9iQqInY8btd4CYfkq/NZOL+s5VmE+fzk+DQHfMarbJs8ZAYJnFkdwHmYw4BwA=
    username: AgCVrJZn+PnADOdPMg6rKyEmrVEtnV4Thw46E5mVKN7TIEL0qs5poxeM3mTvjWpEIgHjMAD8iRTnp4NKaMOs+6N8MAvTeDaCRpByZPEjCVwq4mDzBq2ORWXUH78UM68iXMnfv3Et5h0rwxbv92q/mMLQ4UdC6UciFuy6ERAA8dpkjgXPUHXm08eI7vciVNI1mLEqgH1xJoxn/wFLK0SbD6/F9y1vMdcoHcX3GDjmjY/u4V0nVAldZ0WcpuICl2biS4IRrQGbv/hJ1LZGOa1ppA+qYOGv7FMOVEM8onX+Q+6KqdYwmIs4daRbox1ciyyMvwmI9V9jKxv6SDDA764qR0x7cW/+r5Nu5drwRQeWEV2NV4m26LreHjZxR1bj2lZuidM1OLYo1LjPddwh5yECtV5M3VxYqIxkiVHWXV6qUsrE/YsGzbpsVsGJCeSZGivH4XMwjq+q/rhBIXVjNecKnG4I0zU//K7r0kzZtgnUcovKXnDJ9+m8rx50UByDSPQP3AWO7PyBPglMIEwwtigLAHE3yhw+HPSO0nBthoBncpv8bWB8TWMkfXLInwcNGdwQ0sEz6go2GdFMF6y75goPpnjEMmyie5UiM0JhCBrfEcoUSfOJiWILYuOFh8/ncmUSFuSyyhqUXfuvOhWk4bwV4duj0yC/X48o+38D0c7z2+W/usBhq8h463aoyvY90E1anqJ72elkOg==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: keycloak
