---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnelToken: AgCzACpBpHLd0ne3YqVeXRTWrqlntOgOydSJNZIH2/OLyrVqFTNQGc3vnHGMS69AkJXLkP1gNAxk/G+ZsHaOlEDCKEO+At8vZMg164Gahx9WNlzESXENlHoPdlvVG/g5LMaWSPLpew8iQ1cnRwq18RLgKZ0MiQw6ZtL4yiRR1jI++EPCpMK3ilV4IPq7j6MYIzjL1RlWvFVIxmbsourTQdovJWy+wnD+dgDrxJtMGXlRArBSb6fBGm755lvOdAAJl86Agi8EjorZvPdjHwp5kbf+XOheLJBS/bpC6xc4J5DIUOA8E6Yi7dFvnevZa6XNuj0H+nxKPhLydc2Q2GxjTC7/SrP8bA8XYUxWKB29e5GiCDc5QBEKIx8UISQMVwLgIcliE7DaUnTGVkX1iXzLHPXO72W8ph6uQPQCRPErr4TxnZWGQdqHq+dQErnRg8D/w12njVL+8LYL6AJS/kweV8Iviqetd1KXD/aoM1lf4wWwLW3v85I7vzUXjumVzI7y858XmZkkfsesdjVRXBoXJbcn7s5fTeR5F0yhehVQkDRQVGFIOjjbVJUw2kjLUKA9b9kdzX8seUlPvHTqpOgpDVkcNygCzhXvkxns+H+8zxxe8TKQJaEtBxGzFSeYiMhNNPYZPg6uMxfgVjh95fy/frmd+L4oZBFhSlvpVicH+NuDHwJSE8k+eCHbRSln47m3JALOrU1vcmI3gmGYhbHBMiyFRXRK3oXBGLC2BNoaeI+FF7zQ+m2IYg5xDgc/E1YTIp1h4Ejqx4njimcDW9jXgkyGzwwSRJVcu70yJMfKUTvwFoa/sVA2jpZVg/OrV5rpfDdAndKp0WQeNBdc5xGwQm/I7UUGyy8jeVLVR4PzOLIplLo830FHxqIX2wucs4hV7CBtHlBczl9iDKvPvuiGzvn0UZz3OlUXr00OTmpVqI7QpQORVc6lWmli
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
