---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-cloudflare-tunnel-cloudflare-tunnel-remote
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnelToken: AgCYjjTxWvOVP2pUVcg1e/cEHeLe3wIdtm8qPqGVJKG2OUgU2XJDAeE/38fwFyTKSHFR8hAgcJCOl8sR6E2rZD0ejksbtXlBYyKdzEMVtMbyuvVghnRIWewM8EcKLwW3C7gZyzs4iWQLOkL1JecKQwPZq11L3zaIQy5quN6YuavvUcitd1guwOrv/Dj8hEmYwfLZXnaw86/if7N7JrG9ffR80JJcqR1ptklqqs63gk/G5Gl/PgTZC9diwCVbCw3aU4yvABQeGz8aMHzluCuCE+Y0z0ZMpvyIv4uGfHbv4CEdJUUW7oeGh+xRx07/L3C1CWrF97wnkTiV9WhGdidVsgfgEomJ3WHM1rLfmLUuM8n3vw2yVTJFM3Id9/hvndU0zZeqTEtvxm5B9S5RG8gDqGgAdt5yydGLq+c3JYOz+JxioElEdi6WWCb/xXoGpaI6Q+38bz/ULBTGUSxiALft8otKdZjuhZlxc34ISuD+XD4KkIZ2FRKuOppY0x+TFfnR9skTD+MbFX6Ixi/IDn2BKdkHxgkECd11Qtc5o4YJtd89GgQIVgGHdwDcK5ftDSnJ5OIDyC2XxufHnTBiF8UHcsEwUofitwY+sFX09a58zcgHGOIPniI3YZFkcMaiYb3LyK3AeRrhy2tCVARmGVz4wIoA7d8THSSitz+cRm9hImb1sTvy7XmeF3B3vxd+W6y7NYEae62Es3hF+zKgC3voFDGtZI+K6ctMTTAsZg+lE1r2miY5DTFSKmlWiLkiU5uJMLGVIVFtQ+/Gegm+vYNdRyvZJnfry+56r2bv6kqp60dk/VhRysX79kLekX9Aa7gvlxqXpMXf90wLkoeY8ZHCXlVzASn2XVto+MFA/MSwBt0w8cv2GRrxu8+/RzvclD/b0VLGpEf8vbM1GWVjx9ujyepvu1E05DLR++xxsrqL8DYBO5Lrbg7UrqlR
  template:
    metadata:
      creationTimestamp: null
      name: platform-cloudflare-tunnel-cloudflare-tunnel-remote
      namespace: cloudflare-tunnel
