---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnelToken: AgBIRD/w5in0uOuriTUCmZLkAkpwkkfiY243874eZZoyC99g3Vp+orcjBfSYLjUiK/RKN0ZzP5tzY2aRuabnuJRfA4KfucyxYLhzS91Z7LtHRPmG6JmKKCa+GZ8FWbzZ/EU8XQVmHDBDXBf23/zYKn21IacVQVy1sSx3XscJlurKlfCKvx83ii/PeR/w92Khqiwbh+qx093s/kk53nO8JFDVxSgiC1tCV7x6iqLcGTpI8TP8wPEWzLybdzDs0ga/RVTBx5T0n5wZOTWz9RWwJq18zstIhDoJwpB3wAxCd/mbaGfiRoTX52gDhttTRKuS4ua23u7yRxzwW1CoQ1DWM2zG+ucU7YkXEUI/J0u142Z/EvDzp6FWzp1/tqQggY9gnVm/ECjrODxkzB2thxzKjRaUM3erW1IppdDbuy7PxVWwmZTWzjMGSWf7tYN6CvFegnD4tVs/3BFSDxuA16Wn0eeJrl5BhyNZDzjaCm3jXXzwj8RqGHMgX5tVcp3HdSog0nGF0QdiZvjqs8LvPk4ifTACkGjp/HppqapWfa/Yo8+yIx+46G4Ld4Bf9WLi5C+kYSMLLOlDr+zORUQzUBORxKl5MydexOQYZUJ03HI/yG6B+IiQM0fQBYFzPsCFGDV4cRtvxfkKJRaf1Ff5uc8Qad7FSPHmoBWw3nxYVSHez0OpzhQjF/zI5Il4PR8PH26kvlE9k9Km8000usjmC16wbYJghfZQBlakpL1PF799PMEElD37y/e86yQ63+vqiURSp/oYhs0SliFtBdGSGAfXkcrJEGKAwbg6TrA+qmk6G7Sz0DGa6MY6dgu7lzDUnLE0Y5BOCBzgmvkGS2t2Hvy90hfo0Gu80IbqX/NsRS29BqvKu1s8pWJkFs+L+kjGdx+7SOgomb5p9c6YffyCJ++pdm16LWBVLjllZyBHzn1K+C59ZIW8OTWapkBt
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare-tunnel
