longhorn:
  enablePSP: false
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    defaultReplicaCount: 1
    defaultDataPath: /var/mnt/longhorn
    createDefaultDiskLabeledNodes: true
  persistence:
    defaultClass: true
