longhorn:
  defaultSettings:
    defaultReplicaCount: 1
    defaultDataPath: /var/mnt/longhorn
    createDefaultDiskLabeledNodes: true
  persistence:
    defaultClass: true
  longhornDriver:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  longhornManager:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
