apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.media.storageClass }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.configStorageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app.kubernetes.io/name: gluetun
  ports:
    - port: 8080
      targetPort: qbit-http
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`qbittorrent.{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
